<?php
require('dbConnection.php');

// $sql = "insert into Contacts (FirstName, LastName, Email)
//         values(Xenos,Bryant,pharetra@eleifendnec.ca);";
// $sql .= "insert into Contacts (FirstName, LastName, Email)
//         values('Marry', 'Smith', 'marry@yahoo.com');";
// $sql .= "insert into Contacts (FirstName, LastName, Email)
//         values('Janet', 'Duncan', 'janet@yahoo.com');";   
$sql = "INSERT INTO Contacts(FirstName,LastName,Email) VALUES('Lacey','Price','libero.Proin@tempor.com'),('Amanda','Jefferson','lacus.Mauris.non@volutpatornarefacilisis.co.uk'),('Eaton','Finley','pede.nec@erat.edu'),('Levi','Pugh','pede@elementumsemvitae.edu'),('Jessamine','Richmond','Cum.sociis@tempusnonlacinia.edu'),('Kylan','Langley','vel.nisl@ligulaNullamfeugiat.net'),('Gannon','Luna','dictum.ultricies.ligula@ornareplaceratorci.com'),('Lenore','Mccarty','posuere@ridiculusmusDonec.com'),('Juliet','Love','sed.consequat.auctor@nequesed.net'),('Harlan','Mejia','nulla.ante.iaculis@suscipitestac.net');";
$sql .= "INSERT INTO Contacts(FirstName,LastName,Email) VALUES('Rina','Robbins','sit.amet.consectetuer@acrisusMorbi.net'),('Alan','Lara','ante.ipsum@laoreet.ca'),('Wang','Barrett','Mauris.eu@Maecenasiaculis.com'),('Quincy','Coffey','Ut@sitametnulla.ca'),('Leroy','Bennett','cursus@utmiDuis.org'),('Thaddeus','Delacruz','nunc@sedliberoProin.net'),('Sierra','Robbins','lobortis@Maecenas.net'),('Cassidy','Petersen','fringilla.purus@commodoatlibero.edu'),('Dominic','Solomon','Duis.dignissim@primis.edu'),('Macy','Vance','id.erat@dapibusquam.org');";
$sql .= "INSERT INTO Contacts(FirstName,LastName,Email) VALUES('Wilma','Lewis','Donec.egestas.Duis@adipiscingenim.com'),('Julie','Kirkland','aliquam@adipiscingMauris.org'),('Oren','Russell','ipsum.dolor@urna.net'),('Leroy','Arnold','mi.Duis.risus@arcuSedeu.net'),('Kasper','Collins','Curabitur.vel.lectus@vestibulum.edu'),('Upton','Greene','Curabitur@maurissapien.co.uk'),('Trevor','Oneill','justo.faucibus@euligulaAenean.co.uk'),('Malik','Lynch','in.molestie@Maurisnon.org'),('Inga','Avery','tellus.Phasellus.elit@Nullam.org'),('Leandra','Frank','Vestibulum.ante@sagittissemperNam.com');";
$sql .= "INSERT INTO Contacts(FirstName,LastName,Email) VALUES('Vivian','Adkins','placerat.velit@risus.edu'),('Kai','Cortez','Cras.pellentesque.Sed@egestasligulaNullam.com'),('Mara','Sargent','et.malesuada@orciluctus.co.uk'),('Chase','Deleon','lectus@disparturientmontes.edu'),('Wynne','Duran','sagittis.augue@nonenim.org'),('Gage','Pratt','adipiscing.lacus@ut.org'),('Burton','Buchanan','mollis.vitae.posuere@Nuncmaurissapien.edu'),('Aurora','Vinson','vitae.posuere@elitAliquam.co.uk'),('Bernard','Britt','massa.Suspendisse@rutrum.net'),('Xena','Wilcox','Donec.felis.orci@elitNulla.com');";
$sql .= "INSERT INTO Contacts(FirstName,LastName,Email) VALUES('Germane','Pierce','velit@nasceturridiculus.net'),('Brennan','Hampton','et.euismod@sagittissemperNam.edu'),('Hakeem','Woodard','et.eros.Proin@vitaemaurissit.net'),('Carter','Oneill','vehicula.et.rutrum@purus.ca'),('Thane','Reilly','dictum.placerat.augue@ipsumleo.edu'),('Hayley','Ball','dignissim.pharetra.Nam@orci.org'),('Igor','Floyd','sociis.natoque.penatibus@cursuset.edu'),('Carissa','Mcfadden','urna.justo@Nullatinciduntneque.co.uk'),('Mason','Tate','Phasellus@tellusjustosit.ca'),('Kato','Mcfarland','aliquam@luctuslobortis.edu');";
$sql .= "INSERT INTO Contacts(FirstName,LastName,Email) VALUES('Kuame','Levine','eu@loremfringilla.com'),('Isadora','Mercado','non@duinec.com'),('Yetta','Rivers','tincidunt.nunc.ac@dolornonummy.co.uk'),('Acton','Chandler','purus.ac@pretiumet.ca'),('Denton','Potter','Donec.est@facilisismagna.edu'),('Xanthus','Maddox','ipsum@eutellusPhasellus.co.uk'),('Abbot','Wynn','viverra.Donec@apurus.edu'),('Gabriel','Olson','risus.Donec@parturientmontesnascetur.ca'),('Lance','Neal','erat@Integeraliquam.net'),('Winifred','Woodward','Quisque.libero.lacus@aliquam.co.uk');";
$sql .= "INSERT INTO Contacts(FirstName,LastName,Email) VALUES('Whitney','Maxwell','Suspendisse@Aliquamtincidunt.net'),('Stuart','Barrera','Donec.luctus.aliquet@Uttinciduntvehicula.ca'),('Rowan','White','Integer@orciinconsequat.ca'),('Brenden','Williams','tincidunt.pede.ac@at.org'),('Yvonne','Mcconnell','fames.ac@dictumcursusNunc.org'),('Megan','Fields','ullamcorper.viverra@ullamcorper.net'),('Basil','Mueller','id@Morbimetus.org'),('Blythe','Stone','tempus.lorem.fringilla@temporerat.com'),('Joy','Mcfadden','Integer.sem@posuere.org'),('Octavius','Mcfadden','sed.sem.egestas@nondui.co.uk');";
$sql .= "INSERT INTO Contacts(FirstName,LastName,Email) VALUES('Griffith','Warner','iaculis@enimSuspendissealiquet.com'),('Connor','Leonard','Suspendisse.aliquet@laciniavitaesodales.ca'),('Kim','Olsen','dapibus.id@in.ca'),('Declan','Walters','per.inceptos.hymenaeos@nec.co.uk'),('Trevor','Gill','Donec.elementum.lorem@molestie.com'),('Cathleen','Cline','orci@id.edu'),('Tana','Baker','felis.ullamcorper.viverra@aliquet.co.uk'),('Leandra','Kirkland','Curabitur.sed.tortor@consectetuer.com'),('Alec','Pacheco','ligula.Nullam@magnamalesuada.ca'),('Jorden','Matthews','eu.odio@infaucibus.edu');";
$sql .= "INSERT INTO Contacts(FirstName,LastName,Email) VALUES('Wynne','William','ligula.Nullam@ut.net'),('Mark','Miranda','arcu.Nunc.mauris@semperauctor.edu'),('Mari','Poole','Ut@ac.co.uk'),('Colette','Hess','vestibulum@tincidunt.co.uk'),('Audra','Briggs','netus.et@dui.com'),('Zorita','Morgan','ultrices@mi.org'),('Chadwick','Winters','at.lacus@purusinmolestie.org'),('Hayes','Leonard','commodo.ipsum@facilisiSedneque.com'),('Inga','Horton','erat@Curabituregestas.edu'),('Fiona','Macdonald','purus.accumsan.interdum@nunc.org');";
$sql .= "INSERT INTO Contacts(FirstName,LastName,Email) VALUES('Arthur','Carver','Cras@purusmauris.com'),('Victor','Morgan','nunc@tellus.edu'),('Alvin','Byers','Curabitur@CurabiturdictumPhasellus.com'),('Clementine','Mcdonald','eu.ligula@Quisqueporttitor.net'),('Hiram','Bradford','nunc.sit@Aliquamultricesiaculis.edu'),('Ignatius','Little','Curabitur.dictum@etnetuset.org'),('Keefe','Skinner','sed.leo@amet.ca'),('Seth','Pacheco','tristique@liberonecligula.ca'),('Chava','Jensen','nec.urna@consequatpurus.edu'),('Marshall','Carson','adipiscing@lectusquis.net');";

echo "Connect Successfully. Host info: " . mysqli_get_host_info($conn) . "<br><br>";

if(mysqli_multi_query($conn, $sql)){
    echo "New records created successfully!";
}
else{
    echo "Error: " . $sql . "<br>" . mysqli_error($conn);
}

mysqli_close($conn);
?>